---
title: "Compresión de imágenes y vídeos usando wavelets"
subtitle: "Análisis de Señales. Máster en Ciencia de Datos - UV"
author: "Adrián Carrasco, Clara Montalvá, Javier Herrero, Fabián Calvo y Juan Alcaraz"
date: "Curso 2025-2026"
output:
  html_document:
    echo: true
    number_sections: true
    theme: lumen
    toc: true
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
  bookdown::html_document2:
    echo: true
    number_sections: true
    theme: spacelab
    toc: true
    figure_caption: "Figura"
    table_caption: "Tabla"
  html_notebook:
    echo: true
    number_sections: true
    toc: true
  bookdown::pdf_document2:
    toc: true
    toc_depth: 3
    number_sections: true
    figure_caption: "Figura" # Referencias en castellano
    table_caption: "Tabla"
always_allow_html: true
params:
  lang: spanish
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require("imager", quietly = TRUE)
require("wavethresh", quietly = TRUE)
require("waveslim", quietly = TRUE)
require("magick", quietly = TRUE)
```

# Introducción

# Revisión bibliográfica

# Objetivos

# Descripción de los datos

```{r, include=FALSE}
ruta_acantilado<-"im_2/acantilado.jpg"
ruta_flores<-"im_2/flores.jpg"
ruta_noche<-"im_2/noche.jpg"
ruta_dibujo<-"im_2/dibujo.PNG"

acantilado<-load.image(ruta_acantilado)
flores<-load.image(ruta_flores)
noche<-load.image(ruta_noche)
dibujo<-load.image(ruta_dibujo)
```


```{r}
par(mfrow = c(2, 2), mar = c(1, 1, 1, 1)) 

plot(acantilado, axes=F, xaxs = "i", yaxs = "i")
plot(flores, axes=F, xaxs = "i", yaxs = "i")
plot(noche, axes=F, xaxs = "i", yaxs = "i")
plot(dibujo, axes=F, xaxs = "i", yaxs = "i")
```



```{r}
par(mfrow = c(2, 2), mar = c(0.5, 0.5, 0.5, 0.5))

plot(acantilado_IDWT, axes=F, xaxs="i", yaxs="i")
plot(flores_IDWT, axes=F, xaxs="i", yaxs="i")
plot(noche_IDWT, axes=F, xaxs="i", yaxs="i")
plot(dibujo_IDWT, axes=F, xaxs="i", yaxs="i")
```

# Metodología


```{r, include=FALSE}
source("compresion_IDWT.R")
source("compresion_DCT.R")
source("metricas.R")
```

```{r}
acantilado_IDWT<-compresion_IDWT(ruta_acantilado)
flores_IDWT<-compresion_IDWT(ruta_flores)
noche_IDWT<-compresion_IDWT(ruta_noche)
dibujo_IDWT<-compresion_IDWT(ruta_dibujo)
```

```{r}
acantilado_IDWT<-comprobacion_dim(acantilado, acantilado_IDWT)
flores_IDWT<-comprobacion_dim(flores, flores_IDWT)
noche_IDWT<-comprobacion_dim(noche, noche_IDWT)
dibujo_IDWT<-comprobacion_dim(dibujo, dibujo_IDWT)
```

```{r}
par(mar = c(0,0,0,0)) 

plot(acantilado_IDWT, axes=F, xaxs = "i", yaxs = "i")
plot(flores_IDWT, axes=F, xaxs = "i", yaxs = "i")
plot(noche_IDWT, axes=F, xaxs = "i", yaxs = "i")
plot(dibujo_IDWT, axes=F, xaxs = "i", yaxs = "i")
```
```{r}
acantilado_DCT<-compresion_DCT(ruta_acantilado)
flores_DCT<-compresion_DCT(ruta_flores)
noche_DCT<-compresion_DCT(ruta_noche)
dibujo_DCT<-compresion_DCT(ruta_dibujo)
```

```{r}
#plot(acantilado_DCT, axes=F)
```

# Resultados

```{r}
MSE(acantilado, acantilado_IDWT)
MSE(acantilado, acantilado_DCT)
```
```{r}
MSE(flores, flores_IDWT)
MSE(flores, flores_DCT)
```

```{r}
MSE(noche, noche_IDWT)
MSE(noche, noche_DCT)
```

```{r}
MSE(dibujo, dibujo_IDWT)
MSE(dibujo, dibujo_DCT)
```

```{r}
PSNR(acantilado, acantilado_IDWT)
PSNR(acantilado, acantilado_DCT)
```
```{r}
PSNR(flores, flores_IDWT)
PSNR(flores, flores_DCT)
```

```{r}
PSNR(noche, noche_IDWT)
PSNR(noche, noche_DCT)
```

```{r}
PSNR(dibujo, dibujo_IDWT)
PSNR(dibujo, dibujo_DCT)
```

```{r}
CR(ruta_acantilado, "data_comp/acantilado_IDWT.jpg")
CR(ruta_acantilado, "data_comp/acantilado_DCT.jpg")
```
```{r}
CR(ruta_flores, "data_comp/flores_IDWT.jpg")
CR(ruta_flores, "data_comp/flores_DCT.jpg")
```

```{r}
CR(ruta_noche, "data_comp/noche_IDWT.jpg")
CR(ruta_noche, "data_comp/noche_DCT.jpg")
```

```{r}
CR(ruta_dibujo, "data_comp/dibujo_IDWT.jpg")
CR(ruta_dibujo, "data_comp/dibujo_DCT.jpg")
```

# Conclusiones

# Link del repositorio

https://github.com/JuanAlcarazAED/Trabajo_AS.git
